### PR TITLE
[BUGFIX] Fix indexing without dimension or with custom dimensions

### LINKED ISSUE #112: Regression: indexing fails if no "language" dimension is present
https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/108 introduced a regression by hardcoding the "language" dimension into the NodeIndexer. There are, however, sites which don't have a "language" dimension or which might have dimensions with other names fulfilling the same role like a language.

We need to revert that behaviour or at least make it compatible with other dimension setups.
@dfeyer

### PR DESCRIPTION
**Pull request by dfeyer**
This change fix a regressing who break indexing for site without
dimensions configuration or without the languages dimension.

Fix #112

### CODE REVIEW

File: Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php [hunk 1]
```diff
@@ -259,22 +258,25 @@ public function indexNode(NodeInterface $node, $targetWorkspaceName = null)
...
+            foreach ($dimensionCombinations as $combination) {
+                $context = $this->contextFactory->create(array('workspaceName' => $workspaceName, 'dimensions' => $combination));
+                $node = $context->getNodeByIdentifier($nodeIdentifier);
+                if ($node !== null) {
+                    $indexer($node, $targetWorkspaceName);
+                }
+            }
+        } else {
+            $context = $this->contextFactory->create(array('workspaceName' => $workspaceName));
+            $node = $context->getNodeByIdentifier($nodeIdentifier);
```
Comment (daniellienert) [inline Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php]: Couldn't we use the node here directly?

**Comment by daniellienert** [comment]
Great work @dfeyer! :+1: by reading

**Comment by aertmann** [comment]
:+1:
